<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Random;
use App\Breakdown;

class RandomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return \App\Random::with('random')->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){

      $random_num = rand(5,10); //random number of iterations from 5-10
      $returned_name = $this->generateName($random_num); //Random name based on number generated by its value

      $random = Random::create([
           'values' => $returned_name,
           'flag' => 0
      ]);

      $random_id = $random->id;

      $returned_alphanumeric = $this->generateAlphaNumericString(); //generate a random 5-character ( alphanumeric ) string

      $breakdown = Breakdown::create([
           'values' => $returned_alphanumeric,
           'random_id' => $random_id
      ]);

      return response()->json([
        'number_generated'=>$random_num,
        'alphanumeric'=>$returned_alphanumeric,
        'name_generated'=>$returned_name,
        'success'=>"Success"
      ]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function generateName($random_num){

      $names = array
      (
          'Hello',
          'Wheels',
          'Round',
          'Swirl',
          'long!',
          'TestData',
          'Hiiiiii',
          'Louissss',
          'Foxxyyy',
          'RoundRound',
          'HelloHell',
          'test'
      );

      $match = [];
      foreach ($names as $name)
      {
          $length_string = strlen($name);
          if ($random_num == $length_string)
          {
              $match[] = $name;
          }
      }

      return !empty($match) ? $match[array_rand($match)] : '';
    }

    public function generateAlphaNumericString(){

      $alphanumeric_string = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';

      return substr(str_shuffle($alphanumeric_string),
                   0,5);

    }

}
